### ISSUE TITLE
read_xml.response(x$response, ..., as_html = as_html) : Forbidden (HTTP 403).

### ISSUE THREAD

**Issue by arunrajes** [melissanjohnson/pupR#1]
Hi melissanjohnson

I get this error after calling pupR function.
`> library(pupR)
Welcome to pupR! Pictures taken from pixabay.com
> pupR()
Error in read_xml.response(x$response, ..., as_html = as_html) : 
  Forbidden (HTTP 403).
In addition: Warning message:
In request_GET(session, url) : Forbidden (HTTP 403).`

**Comment by GrantInnerst** [comment]
Thank you very much for letting us know! The website it was scraping changed its permissions. I just pushed a commit that should fix the problem and add more functionality!

**Comment by arunrajes** [comment]
Hi ,

I still receive the same error. even after I re-run this code
`devtools::install_github("melissanjohnson/pupR",force=TRUE)
library(pupR)`

These packages have more recent versions available.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: stringi  (1.4.4 -> 1.4.5) [CRAN]
5: jsonlite (1.6   -> 1.6.1) [CRAN]
6: mime     (0.8   -> 0.9  ) [CRAN]
7: rlang    (0.4.3 -> 0.4.4) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
3

`√  checking for file 'C:\Users\gssaruba\AppData\Local\Temp\RtmpScp8LQ\remotes31142bc17b3e\melissanjohnson-pupR-148db1f/DESCRIPTION' ...
-  preparing 'pupR':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'pupR_0.2.0.tar.gz'
   
Installing package into ‘C:/Users/gssaruba/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'pupR' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'pupR'
    finding HTML links ... done
    pupR                                    html  
    rottweileR                              html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (pupR)`
`library(pupR)
 pupR()
Error in read_xml.response(x$response, ..., as_html = as_html) : 
  Forbidden (HTTP 403).
In addition: Warning message:
In request_GET(session, url) : Forbidden (HTTP 403).`

**Comment by GrantInnerst** [comment]
Hmm... That's odd. When you run the library call for pupR in a fresh session of R, what does the startup message say?

**Comment by arunrajes** [comment]
`library(pupR)`
Welcome to pupR! Pictures taken from free-images.com
`pupR()`
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: free-images.com`

**Comment by GrantInnerst** [comment]
That's interesting that you got a different error this time. I have download the package on multiple machines across platforms (Mac and Linux), and haven't faced any problems. It doesn't look like it, but is it possible that you have a version of the function saved in the global environment that is masking the new function?

**Comment by arunrajes** [comment]
Its working now...I am able to see a cute dog pic in my R Studio
[pupR_Package.docx](https://github.com/melissanjohnson/pupR/files/4159842/pupR_Package.docx)


`sessionInfo()`
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2    yaml_2.2.1   
[pupR_Package.docx](https://github.com/melissanjohnson/pupR/files/4159834/pupR_Package.docx)
